### ISSUE TITLE
The question about SukiSideMenuItem's SelectedIcon

### ISSUE THREAD

**Issue by programClown** [kikipoulet/SukiUI#110]
Hi, kikipoulet

Can SukiSideMenuItem be kept as its origin icon when `HeaderContentOverlapsToggleButton` clicked, not `content:Icons.CircleOutline`.

And when i removed `suki:SukiSideMenu.HeaderContent`, as you see, the `HeaderContentOverlapsToggleButton` overlap with first menuitem, would you change it stay in one row stand alone.

thanks.

**Comment by programClown** [comment]
And, i think sideMenuItem should be add a tooltip property

**Comment by sirdoombox** [comment]
It's already possible to use `ToolTip.Tip` attatched property on `SukiSideMenuItem`.

As for the styling issues with the side menu, it's something that should be looked at, I agree with you and I think the side menu needs a bit of a redesign.

**Comment by kikipoulet** [comment]
The HeaderContentOverlapsToggleButton property will be removed to keep one consistent design.

I will take a look at the selected animation when sidemenu is reduced because the Circle icon is indeed not ideal. It's a bit quirky because it's the same LogoContent for both reduced/expanded states, and I want to keep the selected animation when expanded, but a slight change is needed.

**Comment by kikipoulet** [comment]
done in 6dc1d07

**Comment by kikipoulet** [comment]
With some additional change to remove the ugly scrollbar, it now behaves like this

![sukiside behavior](https://github.com/kikipoulet/SukiUI/assets/19242427/420a1fa6-aa64-4a68-a0b2-bbfe8488c811)
