### ISSUE TITLE
PropertyGrid how to add a AvaloniaList data?

### ISSUE THREAD

**Issue by programClown** [kikipoulet/SukiUI#112]
Hi kikipoulet,
  
How to extend the type of PropertyGrid? Such as AvaloniaList<T>.

**Comment by Insire** [comment]
It looks like thats currently not really possible, because i sealed [this](https://github.com/Insire/SukiUI/blob/main/SukiUI/Controls/PropertyGrid/InstanceViewModel.cs#L10). Gonna open a PR for this. Once thats unsealed you can extend the PropertyGrid as follows:

You have to extend the ``PropertyGridTemplateSelector`` by either subclassing, or wrapping it in your own implementation of a ResourceDictionary implementing ``IDataTemplate``. Then assign your new type as seen [here](https://github.com/Insire/SukiUI/blob/main/SukiUI.Demo/Features/ControlsLibrary/PropertyGridView.axaml#L27) so that it its being used.

All the new types you want to support have to provide their own
```xml
<DataTemplate x:Key="SomeNewTypeViewModel" DataType="yourNameSpace:SomeNewTypeViewModel" />
```

and you need a new corresponding ViewModel ``SomeNewTypeViewModel`` per type aswell.

And finally, you need to subclass the InstanceViewModel, so that that can create your new ``SomeNewTypeViewModel``.

**Comment by kikipoulet** [comment]
> It looks like thats currently not really possible, because i sealed [this](https://github.com/Insire/SukiUI/blob/main/SukiUI/Controls/PropertyGrid/InstanceViewModel.cs#L10). Gonna open a PR for this. Once thats unsealed you can extend the PropertyGrid as follows:
> 
> You have to extend the `PropertyGridTemplateSelector` by either subclassing, or wrapping it in your own implementation of a ResourceDictionary implementing `IDataTemplate`. Then assign your new type as seen [here](https://github.com/Insire/SukiUI/blob/main/SukiUI.Demo/Features/ControlsLibrary/PropertyGridView.axaml#L27) so that it its being used.
> 
> All the new types you want to support have to provide their own
> 
> ```
> <DataTemplate x:Key="SomeNewTypeViewModel" DataType="yourNameSpace:SomeNewTypeViewModel" />
> ```
> 
> and you need a new corresponding ViewModel `SomeNewTypeViewModel` per type aswell.
> 
> And finally, you need to subclass the InstanceViewModel, so that that can create your new `SomeNewTypeViewModel`.

Many thank for your contribution and explanation :+1:
