### ISSUE TITLE
DatePicker control, default formatting

### ISSUE THREAD

**Issue by curvedspace** [kikipoulet/SukiUI#12]
Not sure if I am doing something wrong here but when I use the DatePicker control with SukiUI the dropdown is not very readable, looks like the last character is getting chopped off.  I am using version 4.5.3 on Linux and Windows.

The DatePicker:
![datepicker1_2022-12-31_14-23](https://user-images.githubusercontent.com/3098311/210152590-55302979-dd04-498f-9178-908a15692a64.png)

When I click the control, the dropdown opens (and works) but it is not easy to read. In order to select the date you have to scroll up or down, click on the checkbox does not select/unselect. 

![datepicker2_2022-12-31_14-23](https://user-images.githubusercontent.com/3098311/210152639-de79901c-150f-4b79-8e67-9db8c9d338f5.png)

**Comment by kikipoulet** [comment]
Hi !

Well, I didn't know there was a DatePicker control, which is cool in a way, I will style it later in the library look 👀

About the chopped character it must be because of the listbox style with checkbox of SukiUi by default. Not a big problem, I will make the listbox style optional so the checkbox will not be here on the DatePicker.

I will probably do it tomorrow and upload a Nuget package 👍

**Comment by curvedspace** [comment]
Thank you very much!

**Comment by kikipoulet** [comment]
I styled it like this :

![datepicker](https://user-images.githubusercontent.com/19242427/210170951-f11d350f-6938-4be9-b607-8e6d8f00362f.gif)

I will upload a 4.5.4 nuget package later today
