### ISSUE TITLE
Add a sample of the sidemenu

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#121]
Wish to have an example of the sidemenu in 6.0 version.

I want to add some custmized content to the sidemenu, but there's no exact sample for me to learn.

**Comment by kikipoulet** [comment]
Have you seen the example in the wiki ? https://github.com/kikipoulet/SukiUI/wiki/3.-Controls#sidemenu

Don't hesitate to ask if you need more

**Comment by janjanusek** [comment]
- How can I keep icon of the selected menu item visible (because when I close side panel icon dissapears so it's empty space in there)?
- What property should be set if I want to set selected page programmatically? I really don't like that I should define it in SukiSideMenuItem.PageContent.
- How can I define my own custom background? (I don't like those bubbles and I would like to use my own static color)

Thanks

**Comment by kikipoulet** [comment]
> * How can I keep icon of the selected menu item visible (because when I close side panel icon dissapears so it's empty space in there)?
> * What property should be set if I want to set selected page programmatically? I really don't like that I should define it in SukiSideMenuItem.PageContent.
> * How can I define my own custom background? (I don't like those bubbles and I would like to use my own static color)
> 
> Thanks

1. if you're on 6.0.0-beta2 this is a little issue already solved by 8f55ced8421fe8866c4e6d222e6bb3bfd4ac63d0
2. You can use MVVM and bind your sukimenuitems - see the SukiDemo project
3. The easiest path if you want to simply hide it is to cover it with a Grid with a static color :| 

However, if you have a deeper design idea in mind, note that the "bubble background" is a "SukiBackground" object https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/SukiBackground.cs 

that has been implemented ingeniously by @sirdoombox to be able to have other renderer in the future if needed. Current one is https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Utilities/Background/FastNoiseBackgroundRenderer.cs

So you can create your own renderer if you need something even more specific to your taste.

**Comment by janjanusek** [comment]
1. Will be there soon update? Because yes I do use Beta2 which has this problem.
2. Is there some docu I could Follow on this? Cannot understand how this code generated ActivePage mechanism works.
3. Well ussage of the Renderer is not an option because it's hardcoded within private readonly field, so I tried to use Grid as you mentioned (wrapped SukiSidePanel) but then I have still window title bar in old collor. What do you suggest?

**Comment by kikipoulet** [comment]
This is an open-source project. If you need urgently to make some changes, I suggest you to fork the repo and modify the details to your needs like replacing the SukiBackground in the SukiHost control with a simple Grid with static color.

**Comment by janjanusek** [comment]
You are correct, sir. Thank you for fast responses, very much appreciated.

I was able to change Background color this way within 1 minute 👍

**Comment by kikipoulet** [comment]
No problem, do not hesitate to ask further questions if needed :)

**Comment by yuzh0816** [comment]
> Have you seen the example in the wiki ? https://github.com/kikipoulet/SukiUI/wiki/3.-Controls#sidemenu
> 
> Don't hesitate to ask if you need more

Thanks, I've missed the wiki. The document has solved my issue.
