### ISSUE TITLE
Acrylic\Mica background in MenuFlyout? 

### ISSUE THREAD

**Issue by nikolaykusch** [kikipoulet/SukiUI#148]
Is there a way to use Acrylic, Mica, or just Blur background in a MenuFlyout?

**Comment by sirdoombox** [comment]
Out of the box, no. There's nothing stopping you creating your own style though if you want, just copy-paste the one in SukiUI and alter the background.

Some attempts have been made to use a transparent/blur effect for controls internally but the performance hasn't been particularly good where it's been tried.

I'm sure we could take another stab at it to see if there's a way it could be an option at least, though we might bump up against performance issues again or just find it involves changing way too much of the design to the point that we have to maintain essentially two styles.

**Comment by nikolaykusch** [comment]
Honestly, I don't quite understand how this can be done. In the Avalonia documentation, it only talks about TopLevel and the TransparencyLevelHint property. But in Avalonia.Themes.Fluent, the required effect is present.

**Comment by kikipoulet** [comment]
Earlier, our GlassCard was a real glass card, like this one in CherylUI -> https://github.com/kikipoulet/CherylUI/wiki/2.-Controls#glass-card

You can still find the code here -> https://github.com/kikipoulet/CherylUI/tree/master/CherylUI/Controls/GlassMorphism

However, in SukiUI, we "rollbacked" into using a simple tinted opacity card showing a "fake" effect of glassmorphism on top of our custom Mica-like background implementation because it cost a little performance and it showed very weird lines on big screens blurs. This is why our fake glassmorphism style doesn't have it extented to dialogs combobox and flyouts, even if at some point it did.

My "design" advice for a flyout or a dialog is to use the SukiBackground control which is basically our Mica-like implementation. It will show a background of the same style of the SukiWindow.

Hope it helps.
