### ISSUE TITLE
Error in preview5

### ISSUE THREAD

**Issue by j4587698** [kikipoulet/SukiUI#20]
```
System.MethodAccessException: Attempt by method 'ReaderAvalonia.App.!XamlIlPopulate(System.IServiceProvider, ReaderAvalonia.App)' to access method 'CompiledAvaloniaXaml.!AvaloniaResources.Build:/Theme/Index.xaml(System.IServiceProvider)' failed.
   at ReaderAvalonia.App.!XamlIlPopulate(IServiceProvider, App) in App.axaml:line 11
   at ReaderAvalonia.App.!XamlIlPopulateTrampoline(App)
   at ReaderAvalonia.App.Initialize() in App.axaml.cs:line 16
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 248
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 160
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 211
```
preview5 maybe modify something...

**Comment by kikipoulet** [comment]
Absolutely preview5 has some breaking changes. 
I quickly checked and for example I have to remove all "ItemTemplate" and "Items" properties from ItemsPresenter, and it works the same, don't know why ._.

I will make the changes and create a new nuget package this week from preview1 to preview5 to be up-to-date. But I don't want to go too fast because I have to update the documentation because of the new "InteractiveContainer" control that changes and simplify the way to show Dialog and Toast for Desktop and Mobile, which was a horrible duplication of code before. 

By the way this "InteractiveContainer" should be a good way to add some interactivity features. Dialog and Toast already, but maybe more soon - Notification, SnackBar, BottomSheet, ..

**Comment by j4587698** [comment]
@kikipoulet This is definitely good news.
I'm also waiting new InteractiveContainer，because sometimes I can't use DesktopPage but want to use Dialog.

**Comment by kikipoulet** [comment]
Suki 4.6.0 nuget package is uploaded and works with preview5 now.
I also updated the documentation because using Dialog and Toast is different now.

About InteractiveContainer; there are still two main limitations now :
- you can only have one in your App, in your MainWindow/MainView
- Dialog can't be stacked, you can't call a dialog inside a dialog. (Well, original dialog will be replaced). It can be a problem while using some Mobile Controls, a Picker can't be called from a Dialog right now for example.

I'm planning to solve these two limitations someday, but not immediately, so it is just for informations purpose 👍
