### ISSUE TITLE
[Bug] An open dialogue with allowBackgroundClose set to false prevents access to the window bar

### ISSUE THREAD

**Issue by nicki419** [kikipoulet/SukiUI#226]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

When creating a dialogue with `allowBackgroundClose` set to `false`, it is impossible to move, minimise, maximise, or close the window. 

### Package Version

6.0.0-beta7

### Environment

Win11, GNU/Linux (Gnome on Wayland)

### Expected Behavior

The Window's Titlebar should still be clickable and preserve its functionality.

### Reproduction

```csharp
SukiHost.ShowDialog(new ArbitraryDialogueViewModel(), allowBackgroundClose: false);
```

### Additional Information

Dialogues are great to use as an introduction to one's application: 

<table style="border:none">
  <tr>
    <td> <img src="https://github.com/kikipoulet/SukiUI/assets/20019984/1b77735c-87b1-4f68-b37e-49d3f99af192"  alt="1" width= 480 ></td>
    <td><img src="https://github.com/kikipoulet/SukiUI/assets/20019984/93588e9a-5cb2-41de-9b5a-5154def850b1" alt="2" width= 480 ></td>
   </tr> 
</table>

Thus, it would be great if the end user wasn't prevented from moving/closing the application until they finish the intro.

**Comment by sirdoombox** [comment]
This I think becomes more of a developer implementation issue. The design and functionality of the dialogs are such that they completely dominate the window and trying to "extract" the title bar or add fake close buttons on top of the dialog overlay wouldn't really align with what we were going for with them.

My recommendation would be adding an "Exit" button so that it's crystal clear to the end user that if they exit without setting up the application would close, which would also preserve the design intention of the dialogs.

Alternatively you could use a full window for the setup process which would give you full window-level controls if you're looking for that.

**Comment by nicki419** [comment]
@sirdoombox I understand what you are going for here, and I see value in dominating the window, as to prevent the user from clicking through and accessing other controls. Makes sense. However, I still do not understand the idea on why this would have to apply to the titlebar, ignoring my implementation here. While I can't name one from the top of my head, I've had other applications use a similar thing which still allowed me to move the window around, resize it, etc. I think having that as an option when initialising the dialogue would be nice.
When creating a custom titlebar from scratch, for instance, you have the `IsHitTestVisible` property.

**Comment by Insire** [comment]
The ``ShowDialog`` methods are modeled after their correspondents from other gui frameworks, such as WPF or Winforms. I agree with @sirdoombox that we should not alter/extend the ShowDialog API for something thats an oversight in your project.

If anything, there should be a new API and terminology for a dialog, that doesnt behave like a dialog, Maybe ``ShowOverlay`` could be acceptable?

**Comment by sirdoombox** [comment]
The dialog host is positioned at the absolute root of the window, the titlebar is contained with in it. In order to enable the titlebar we'd have to pick one of these not very good options:
- Make the dialog background click through, with no visual changes this would be confusing and would break a lot of existing behaviour.
- Completely reorder the visual tree so the dialog host is within the main body of the window, disabling the ability to make the dialog an absolute requirement and creating a disjointed visual at the top of the window. This would also be a non-optional behaviour.
- Re-draw a custom title bar on top of the dialog with a new solid baclground, as the existing one relies on transparency and would look odd being re-drawn above.
- Include an optional clear grid space at the very top of the dialog host which can be used to "expose" the title bar - this is probably the least awful of the options but would be a massive headache to implement properly and look terrible as with the top menu enabled the title bar itself has no defined "end". Even worse still when you consider the bottom border can be enabled/disabled.

None of these options really make much sense from our end, especially as you can very, very easily re-implement the dialog host within whatever scope you want if that's the behaviour you're looking for, or as I said you can simply create a new window specifically for your flow or just add a button into the dialog to exit out of the application.

I would seek input from @kikipoulet on this one but I believe we had discussions about the exact way the dialogs would look and feel fairly on and made the call to go with this for simplicity and visual reasons.

**Comment by kikipoulet** [comment]
Sorry for being late, I'm in vacation. Basically I confirm that the current overlay is on purpose, we do not want to have a title bar visible while showing a modal.

So I think that precise use case shouldn't be included in the library, and for tutorial purpose I would even advice the use of Popups that are more flexible.
