### ISSUE TITLE
[Bug] StackPage forgets its stack when navigating in a SideMenu parent

### ISSUE THREAD

**Issue by BlossomiShymae** [kikipoulet/SukiUI#264]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

While deep in the StackPage, navigating between pages in a SideMenu parent can cause the StackPage to forget the stack.

<details>
  <summary>Attached GIF</summary>
  
  ![bug](https://github.com/user-attachments/assets/baa1b6da-c06d-4f74-86cb-7f67fd966da8)
</details>

### Package Version

6.0.0-beta7

### Environment

Windows 10.0.19045

### Expected Behavior

Expected the StackPage to remember its stack content.

### Reproduction

- Navigate down in the StackPage
- Navigate other pages in the SideMenu parent
- Go back to the stack page.

### Additional Information

https://github.com/BlossomiShymae/Needlework.Net/tree/0.3.1.0

https://github.com/BlossomiShymae/Needlework.Net/blob/0.3.1.0/Needlework.Net.Desktop/Views/EndpointsContainerView.axaml#L12-L13
https://github.com/BlossomiShymae/Needlework.Net/blob/0.3.1.0/Needlework.Net.Desktop/ViewModels/EndpointsContainerViewModel.cs

**Comment by AuroraZiling** [comment]
I can't reproduce this issue in demo

**Comment by kikipoulet** [comment]
I haven't met such behavior before too, it would help to have the repo

As a side note, don't hesitate to share some screenshots of your designs with SukiUI (as I see you have already a software quite complete), I like to see what people's do with SukiUI

**Comment by BlossomiShymae** [comment]
> I haven't met such behavior before too, it would help to have the repo

I have included links to the repo in the OP.

**Comment by kikipoulet** [comment]
I think we need @sirdoombox , it seems to be related to MVVM and SideMenu behavior.

**If I remember well**, the SideMenu keeps the last page in a cache, so when going back again, it is the same View instance. Nothing change.
But when your page isn't in the cache anymore, it seems to create a new View instance, with a new StackPage instance, that display directly the same "activePage" from your VM, but losing the page "history" that is in the StackPage control.

So actually it is the correct behavior, to be honest I don't really understand why it does _not_ happen in SukiDemo too, but @sirdoombox knows this part wayyy better than me

**Comment by sirdoombox** [comment]
I pulled down your Needlework.Net repo and reproduced the issue locally. I confirmed that it's an issue with the cache and a new view being created however your ViewModel retains it's state. We don't suffer from this issue in the demo app because all our pages are cached on-load so everything runs nice and smooth, this has the added benefit of holding any view-related state in place which is ideal for us.

I can take a look to see if there's some mechanism we can use to keep the stack in-scope. _**However**_ it's not necessarily a good idea for us to do this as generally speaking we want developers to have full control over the lifetime of their view. As a temporary fix I would recommend that you cache your views in some way if this behaviour is important to you.
[Here is a link to our ViewLocator source which we use to cache views.](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI.Demo/Common/ViewLocator.cs)

I would suggest at this point that if we wanted to allow people to retain the state we have three possible options:
1. Expose a property that would allow devs to bind a collection in their ViewModel to the stack - in one-way from source mode - so that the lifetime of the stack could be tied to the lifetime of a ViewModel. This might also open up the ability to manipulate the stack directly if we make it read/write.
2. Build some internal system that relies on the parent control's datacontext so that when the data context is changed the stack is only cleared at that point, otherwise it's retained statically across instances.
3. Simply suggest that people cache their views if they want view state to persist.

Option 2 is likely to be a bug-inducing nightmare and not worth the effort, whilst option 1 is probably the sanest if we want this behaviour to be available "out of the box" - however it will rely essentially on a weird side effect and/or require an API change for the stackpage control. Option 3 is a strong choice because in general you do want devs to be responsible for the lifetime of their views.

**Comment by kikipoulet** [comment]
> I pulled down your Needlework.Net repo and reproduced the issue locally. I confirmed that it's an issue with the cache and a new view being created however your ViewModel retains it's state. We don't suffer from this issue in the demo app because all our pages are cached on-load so everything runs nice and smooth, this has the added benefit of holding any view-related state in place which is ideal for us.
> 
> I can take a look to see if there's some mechanism we can use to keep the stack in-scope. _**However**_ it's not necessarily a good idea for us to do this as generally speaking we want developers to have full control over the lifetime of their view. As a temporary fix I would recommend that you cache your views in some way if this behaviour is important to you. [Here is a link to our ViewLocator source which we use to cache views.](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI.Demo/Common/ViewLocator.cs)
> 
> I would suggest at this point that if we wanted to allow people to retain the state we have three possible options:
> 
> 1. Expose a property that would allow devs to bind a collection in their ViewModel to the stack - in one-way from source mode - so that the lifetime of the stack could be tied to the lifetime of a ViewModel. This might also open up the ability to manipulate the stack directly if we make it read/write.
> 2. Build some internal system that relies on the parent control's datacontext so that when the data context is changed the stack is only cleared at that point, otherwise it's retained statically across instances.
> 3. Simply suggest that people cache their views if they want view state to persist.
> 
> Option 2 is likely to be a bug-inducing nightmare and not worth the effort, whilst option 1 is probably the sanest if we want this behaviour to be available "out of the box" - however it will rely essentially on a weird side effect requiring people to bind to a collection for purely view-related reasons. Option 3 is a strong choice because in general you do want devs to be responsible for the lifetime of their views and this behaviour is technically speaking by design.

I agree, peoples must stay responsible for the lifetime of their views. Thanks for the explanation @sirdoombox !
