### ISSUE TITLE
[Bug] Toast Messages and Pop up dialogs

### ISSUE THREAD

**Issue by kingnathi112** [kikipoulet/SukiUI#285]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

This is a question, wanted to findout if the way Toast and popup dialog messages will keep on changing for each release, asking so that I create a better handle for these changes,

### Package Version

6.0.0-Beta8

### Environment

Windows 11 22631

### Expected Behavior

For toast messages to not keep changing

### Reproduction

This is question

**Comment by sirdoombox** [comment]
This represents the last major change as far as I'm concerned, the original rewrite was generally only meant to be temporary to get styling in place whilst a more permanent solution was found and this second rewrite was always planned though what form it was going to take wasn't clear until recently and it wasn't necessarily communicated.

Of course 6.0.0 is still a beta release so there might still be some tweaks and changes, but the fundamental design of the API is now set and it's been written and designed so that new features/changes should cause few or no breaks, and any breaking changes should be minimal and planned for major releases anyway going forward.

I'd want @kikipoulet to weigh in and confirm that they are happy with where it's at right now and then you can be confident that this API is unlikely to change in any major way from now on.

**Comment by yuzh0816** [comment]
This api change really made it very difficult for me to adapt it into my project... Every dialog is based on the old one...

**Comment by sirdoombox** [comment]
That's one of the dangers of working with pre-release code.

**Comment by kingnathi112** [comment]
@yuzh0816 same here, I've been struggling to get it working with my project, had to revert back to beta7. Will stay on beta7 until someone makes a tutorial on it :D

**Comment by sirdoombox** [comment]
[Here are the docs for the new toasts API.](https://kikipoulet.github.io/SukiUI/documentation/hosts/toast.html)

The Dialogs API is _very_ similar and you just use `SukiDialogHost` instead of `SukiToastHost`, I haven't gotten around to writing the docs for it yet but the XMLDocs are in place so it should be fairly easy to get on with.

**Comment by kikipoulet** [comment]
I understand your frustration guys but @sirdoombox is completely right, and this new implementation will let us add new features in the future without breaking anything. Furthermore, the fluent builder is quite nice. 


To replace the old way as easy as possible : 

1. Add a SukiDialogHost in your SukiWindow 

![{FD9EF5DB-613B-471D-AAE1-0AB4AEAD9F90}](https://github.com/user-attachments/assets/0986284b-250e-4c37-a469-b6b974df6e7b)

2. Reference it statically in your window

![{206CB8DC-5518-411C-B757-962C78698EE0}](https://github.com/user-attachments/assets/f9a429e2-5feb-4f4c-ae87-e1bc192a7756)


3. Show your dialog "anywhere" in your code from the static reference

```
MainWindow.DialManager.CreateDialog()
        .WithContent(new YourControl())
        .Dismiss().ByClickingBackground()
        .TryShow();
```



So actually it works almost like the toasting documented here : https://kikipoulet.github.io/SukiUI/documentation/hosts/toast.html

**Comment by kingnathi112** [comment]
Thanks, worked :)

**Comment by sirdoombox** [comment]
Closing this as answered for now. If there are any follow ups I'm happy to re-open.
