### ISSUE TITLE
Updating has broken the vm

### ISSUE THREAD

**Issue by sabuto** [kikipoulet/SukiUI#3]
Since updating, and using the desktop page the properties in my main vm, im thinking this is because the datacontext of anything within the desktop page is now DesktopPageViewModel.cs, but im not 100% sure if this is why. but essentially i have a tab view within the desktop page and it doesn't register any of my properties for anything within the desktop page. I hope this makes sense.

**Comment by kikipoulet** [comment]
Yes you're right, maybe it's not very smart from me to have done it like that 😰

At this point I guess it would work to use another View-ViewModel directly in the DesktopPage but it would be great to find a solution.

Maybe there is a way or a property to make the datacontext unavailable for the children so it will use the viewmodel from your view instead ?

Or I suppose there is a way to remove the datacontext from DesktopPage and use something else (inotifypropertychanged) ?

I need to make some research because I don't know enough right now

**Comment by sabuto** [comment]
so at  the moment from what i can see the only thing you are using the vm for is the dialogs, you could do this in a service and put it into the avalonialocator or see  how [materialAvalonia](https://github.com/AvaloniaCommunity/material.avalonia) or [FluentAvalonia](https://github.com/amwx/FluentAvalonia) do it.

**Comment by kikipoulet** [comment]
Fix is available in the nuget package version 2.6.6
