### ISSUE TITLE
Remove/block MessageBox controls and movement

### ISSUE THREAD

**Issue by RivenSkaye** [kikipoulet/SukiUI#6]
Currently the `Info`, `Error` and `Success` message boxes allow maximizing, resizing and dragging around.
This behavior is, especially for error messages, not desirable in my opinion.
Could optional arguments or alternatives be added in order to disallow resizing and set the `MessageBox` to appear on a fixed position of the screen (e.g. Center)?

**Comment by kikipoulet** [comment]
Indeed it is not desirable at all, I didn't give a lot of attention to the MessageBox recently because I personally prefer using the Dialog option from the DesktopPage.

Anyway, I made the changes to the MessageBox to have the right behavior.

See the gif : https://raw.githubusercontent.com/kikipoulet/SukiUI/main/Images/NewMessageBox.gif

I added the WindowStartupLocation as an optional parameter too :

`
MessageBox.Success(this, "Congratulations", "Here is a random success message, youpee !", WindowStartupLocation.CenterScreen);`

I will upload a nuget package version 2.6.8 today
