### ISSUE TITLE
Cloned repository can't be opened without errors

### ISSUE THREAD

**Issue by DmitryGolubenkov** [kikipoulet/SukiUI#8]
## Steps to reproduce
1. Clone the repository
2. Open the solution in IDE

Output:
![image](https://user-images.githubusercontent.com/31821994/194709306-1054aa40-a204-4155-b3c9-60e25afe5330.png)
`One or more projects in the solution can't be loaded properly.`

## Issue
This error occurs because the `Suki.sln` file contains a project named `SukiTest` that was not commited to repository.

## Solution
There are two solutions:
1. Remove the reference to a project from commited solution.
2. Upload the project.

I think that it will be better to upload the project to repository, because when I want to contribure, I need to test my changes. And for that I have to make a new project myself, add a reference to library project, test the changes here, and then choose only some files to commit.
Also, the test application can be used as a sample app where people can test the controls before integrating them into their own application. Many controls libraries have such apps, often named "Gallery". They show all the controls and also provide the XAML and C# code needed used in examples. Some of them are in separate repositories, but I don't think that this is needed for a sample app.

If needed, I think I could build a sample application myself and make a PR, but it will take time.

Also, I think the project should be in folder `/Samples/` or something like that, because there could be a second project to show off (or test) mobile controls that are currently not present in repository, but mentioned in `README.md`

**Comment by kikipoulet** [comment]
Actually the repo is quite outdated unfortunately, 100% my fault, used to manually add the files from the web GitHub interface because I was the only contributor 🥹

So, I will solve it this week, adding the missing projects, the most recent SukiUI code, with your last commits, .. And finally use that Rider Git plugin 🫣 

Good news are :
- Actually I have "updated" the project to Avalonia 0.11 
- I will upload the sample desktop app
- I will upload the mobile app working with Avalonia 0.11

My goal is to have a clean repo this week, sorry for the inconveniences.
I'm 100% aware that it is horrible to contribute right now and my priority is to solve it.

**Comment by DmitryGolubenkov** [comment]
No problem! Rome wasn't built in a day.
The project is great, it just needs some time and work to be polished

**Comment by kikipoulet** [comment]
@DmitryGolubenkov 

I commit in Avalonia 0.11 with my code for Desktop (SukiTest) and a Mobile experimentation (AndroidTest).
I merged the last PR.
Cloned repository can now be opened and used normally.

Little warning about the mobile app - code is awful, it is just a proof of concept and design experimentation. My goal now is to identify and create the mobile controls.
