### ISSUE TITLE
Not able to import the NuGet library v5.3.0 inside a new project

### ISSUE THREAD

**Issue by robertosilviu** [kikipoulet/SukiUI#98]
Hi, 
i'm trying to test SukiUI inside my Avalonia MVVM project, but at the moment i'm not able to import it, when following the official guide. The last version of the NuGet package is 5.3.0. I am able to install it correctly, but when i import it inside App.axaml and use `suki:SukiWindow` inside MainWindow.axaml, i have build errors because the SukiUI dependency is not being found.  I've tried to run the app `SukiUI.Demo` and it works without any problems. 

Do you still need to publish v6 on NuGet? Or am i missing some other dependencies for older versions? I am using Avalonia 11.0.6 and .net8.  Thank you!

**Comment by kikipoulet** [comment]
Hi,

The documentation has been updated very recently for the 6.0 release that is coming and have lots of breaking changes compared to 5.3

We are polishing last details and I expect to publish a NuGet package in few days, at least a preview (because as you've seen, I've already updated the wiki)

Thanks for your patience I hope you'll like it 👍

**Comment by cntseesharp** [comment]
@kikipoulet appreciate your hard work, but it's better to release documentation along with the new version, rather than in advance :D

**Comment by kikipoulet** [comment]
6.0.0-beta available
